--PRIMEIRO EXEMPLO DE SUB-SELECT
SELECT COD_CONTRATO, Trim(To_Char(DATA, 'DD/MM/YYYY')), Trim(TOTAL)
FROM TCONTRATO
WHERE TOTAL >=
  (SELECT VALOR FROM TCURSO
    WHERE COD_CURSO = 3)
--SEGUNDO EXEMPLO DE SUB-SELECT
SELECT COD_ALUNO, NOME, CIDADE
FROM TALUNO
WHERE CIDADE = (SELECT CIDADE
                  FROM TALUNO
                 WHERE COD_ALUNO = 1)
 AND COD_ALUNO <> 1;
--VERIFICAÇÃO DE CIDADES REPETIDAS
SELECT Count(*),ESTADO FROM TALUNO GROUP BY ESTADO;
--TERCEIRO EXEMPLO DE SUB-SELECT
SELECT COD_ALUNO, NOME, CIDADE, ESTADO
FROM TALUNO
WHERE (CIDADE,ESTADO) =
        (SELECT CIDADE, ESTADO FROM TALUNO
          WHERE COD_ALUNO = 1)
  AND COD_ALUNO <> 1;
--ATUALIZANDO TABELA PARA SUB-SELECT FUNCIONAR
SELECT * FROM TALUNO WHERE ESTADO = 'GO';
--ATUALIZANDO TABELA PARA SUB-SELECT FUNCIONAR
UPDATE TALUNO SET ESTADO = 'GO' WHERE COD_ALUNO = 1;
--ATAULIZANDO TABELA PARA SUB-SELECT FUNCIONAR
UPDATE TALUNO SET CIDADE = 'NOVO HAMBURGO' WHERE COD_ALUNO = 5;
--SALVANDO ALTERAÇÕES
COMMIT;
--ULTIMO EXEMPLO DO SUB-SELECT
SELECT COD_CURSO, Min(VALOR), Sum(VALOR),
       Count(*) QTDE
    FROM TITEM
WHERE COD_CURSO > 0
  GROUP BY COD_CURSO
HAVING Min(VALOR) >=
( SELECT Avg(VALOR) FROM TCURSO)
ORDER BY COD_CURSO;

